### ISSUE TITLE
[Question] Where are the `talk_formats` in `SelectTag` defined?

### ISSUE THREAD

**Issue by TMaYaD** [gobuffalo/tags#142]
Like the title says. The documentation on where they are defined is missing.

**Comment by sio4** [comment]
Do you mean the `talk_formats` in the wiki pages below? ([1] and [2]) If then, this is not a part of this package and it is just an example code.

The code below is also an example Model for the explanation. As you see, the model `Talk` has a foreign key `TalkFormatID` which means there could be a separated model called `TalkFormat`. When the application passes the values to the rendering engine, it will also provide that as the name of `talk_formats` (in context value) then the rendering engine will use the value. 

```go
type Talk struct {
	ID            int          `json:"id" db:"id"`
	Title         string       `json:"title" db:"title"`
	Notes         nulls.String `json:"notes" db:"notes"`
	TalkFormatID  int          `json:"talk_format_id" db:"talk_format_id"`
}
```

So in this case, you can just assume there is another Model or just a simple key-value pair with the name `talk_formats`. Then those key-value pair will become a select box.

```erb
<%= form_for( talk, {action:"/talks", method: "PUT"}) { %>
<div class="row">
  <div class="col-md-12">
    <%= f.InputTag("Title") %>
  </div>
  <div class="col-md-6">
    <%= f.SelectTag("TalkFormatID", {options: talk_formats}) %>
  </div>
  <div class="col-md-12">
    <%= f.TextArea("Notes", {rows: 10}) %>
  </div>
</div>
<% } %>
```

I think this document [3] is also a good reference for usage because there is a simpler example:

```erb
<%= f.SelectTag("TalkFormatID", {options: {"one": 1, "two": 2}, value: 2}) %>
```

Could it be an answer?

[1] https://github.com/gobuffalo/tags/wiki/FormFor
[2] https://github.com/gobuffalo/tags/wiki/Form
[3] https://gobuffalo.io/documentation/frontend-layer/forms/#selected

**Comment by TMaYaD** [comment]
Yup, I got that that's an example. But the example is incomplete. The variable is being used but it's not described in the documentation where to define it.

**Comment by sio4** [comment]
Yeah, agree. Since the doc is a part of series of docs, it seems like that part is not on the paticular doc. :-)
