### ISSUE TITLE
How should I bind/add javascript function on select tag

### ISSUE THREAD

**Issue by suhaschitade** [gobuffalo/tags#40]
Hi,
I need to implement cascading dropdowns in my app which is based on buffalo framework. I am using below code for generating countries dropdown

<%= f.SelectTag("Country", {options:countryList}) %>

Now once the user selects the country I want to do a show related states in the country. How should I bind and define function
thanks

**Comment by markbates** [comment]
You can add tag level attributes like this:

```
<%= f.SelectTag("Country", {options:countryList, class: "foo", style: "text-align: right", etc...}) %>
```

The tags will produce `name` and `id` attributes automatically for you, but you can override them in the options hash.

Your JavaScript goes in the `assets/js/application.js` file. You hook into the tag just like you would any other JavaScript/HTML hook since it all runs on the client side.

If you're asking what that JavaScript should look like, I would recommend googling for examples.

**Comment by suhaschitade** [comment]
thank you, Mark. Awesome
In the benefits of other users, I think we should add this extra information in select tag documentation.
Please let me know your view.

**Comment by markbates** [comment]
More documentation is always welcome. :)
